export * from './lib/user.module';
export * from './lib/room.module';
export * from './lib/exercise.module';
export * from './lib/training.module';
export * from './lib/auth/auth.module';
export * from './lib/user/backend-features-user.module';
export * from './lib/room/backend-features-room.module';
export * from './lib/exercise/backend-features-exercise.module';
export * from './lib/training/backend-features-training.module';
