name: Deployment to Azure
on: 
  push:
    branches:
      - main
      - Deployment

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          
      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Zip artifacts for deployment
        run: |
          echo ${GITHUB_WORKSPACE}
          cd ${GITHUB_WORKSPACE}/dist/apps/data-api/ && zip ${GITHUB_WORKSPACE}/data-api-release.zip ./* -r
          cd ${GITHUB_WORKSPACE}/dist/apps/ttvd-trainingen/ && zip ${GITHUB_WORKSPACE}/ttvd-trainingen-release.zip ./* -r

      - name: Upload angular app for deployment
        uses: actions/upload-artifact@v3
        with:
          name: ttvd-trainingen
          path: ttvd-trainingen-release.zip
      
      - name: Upload nestjs api for deployment
        uses: actions/upload-artifact@v3
        with:
          name: data-api
          path: data-api-release.zip
          
  deploy-angular:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
    steps:
      - name: Download angular artifact
        uses: actions/download-artifact@v3
        with:
          name: ttvd-trainingen

      - name: Unzip angular artifact
        run: unzip ttvd-trainingen-release.zip

      - name: Deploy to static azure web app
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.ANGULAR_PUBLISHTOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          api_location: ""
          output_location: ""
          
  deploy-api:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download nestjs artifact
        uses: actions/download-artifact@v3
        with:
          name: data-api

      - name: Unzip angular artifact
        run: unzip data-api-release.zip

      - name: Install npm dependencies
        run: npm install

      - name: Deploy to azure web app
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'TTVD-Trainingen-API-NestJS'
          publish-profile: ${{ secrets.NEXTJS_PUBLISHPROFILE }}
          package: .
